### ISSUE TITLE
Better error handling for network timeouts on asset library called through lambda-invoke

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-connected-device-framework#17]
**Aws Connected Device Framework Affected Module(s):**
 
assetlibrary

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

When asset library is invoked using lambda-invoke, if there is a network connection issue or other problem, lambda-invoke will wait for the default amount of time before retrying (120 seconds, according to [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property)). This will show misleading errors in the calling lambda, as default API Gateway/Lambda timeouts are 30 seconds.

**Current behavior:**

Facade function using lambda-invoke will respond with a 504 Gateway Timeout

**Expected behavior:**

Lambda-invoke retries before default lambda timeout expires. Either lambda-invoke fails after retry and proper error message is returned to calling function, or lambda-invoke succeeds and calling lambda is only slowed down slightly.

**Steps to reproduce:**

1. Use Lambda-invoke to perform an asset library call (like a search or get group)
2. Network (or other) issue causes request to timeout and not make it to asset library
3. Calling lambda times out before lambda-invoke has opportunity to retry

**Additional Information:**

Here's a timeout that occurred. This is a log message of a facade lambda invoking asset library (using lambda). It shows it waited for about 30 seconds until the lambda hit it's timeout.
<img width="805" alt="facade-log-invoke-assetlibrary" src="https://user-images.githubusercontent.com/89797921/135699235-803d6899-2c7f-41b2-8cb1-06bbdf174440.png">
The corresponding asset library logs don't even show any invocation at that time.

**Comment by aaronatbissell** [comment]
I'd like the team's thoughts on this. 

If we think this is a true problem, my suggestion would be to shorten the timeout for the lambda-invoke in the AWS.Config used when creating the AWS.Lambda in `assetlibrary-client/src/di/inversify.config.ts`

```ts
const lambda = new AWS.Lambda({region:config.get('aws.region')});
```

to

```ts
const lambda = new AWS.Lambda({
  region:config.get('aws.region'),
  maxRetries: 2,
  httpOptions: {
    timeout: 5000,
    connectTimeout: 1000,
  }});
```

**Comment by aaronatbissell** [comment]
FYI - I made the above changes and did some testing. I'm still seeing these "Gateway Timeouts" (very infrequently, but it doesn't seem to make an impact)

**Comment by jaychung-aws** [comment]
@boardthatpowder @hassankhokhar Want to get your input when you have a chance. What do you think about the following options?
1) Increase the Lambda Function's timeout so that it provides enough time for the labmda.invoke() SDK call to timeout gracefully.
2) Implement a timeout mechanism in the Lambda Function layer so that it gives up on a hanging lambda.invoke() SDK call, retrying it. Essentially moving the timeout & retry mechanism built-in with the SDK up to the calling application's layer.

**Comment by boardthatpowder** [comment]
Any timeout mechanism will need to be part of the calling function (e.g. facade) rather than the CDF client libraries due to the fact that a calling function my make multiple lambda invocations within the same APIGW execution context., therefore closing this.
