### ISSUE TITLE
Notfication enable/disable function feature request

### ISSUE THREAD

**Issue by tsugunao** [aws/aws-connected-device-framework#26]
**Aws Connected Device Framework Affected Module(s):**
Notifications

**I'm submitting a ...**

- [ ] bug report
- [x] feature request

**Description:**

Currently, disabling notification temporarily is not supported. This is a feature request to disable/enable notifications.  

**Current behavior:**
Currently, disabling notification temporarily is not supported. In the EventResoruce definition, there is an attribute of "enabled", but is is just a placeholder and not being validated currently.

**Expected behavior:**
This is a request to implement a feature to enable/disable notifications by using the attribute of enabled.

**Steps to reproduce:**
N/A

**Additional Information:**

**Comment by williamsia** [comment]
Hi @tsugunao , not sure if you still need this functionality, but this is now available, look at [this](https://github.com/aws/aws-connected-device-framework/blob/main/source/packages/services/events-processor/src/api/subscriptions/subscription.service.ts#L334) for more details. I will close this issue, but do let me know if you have an issue with the implementation
