### ISSUE TITLE
Documentation is missing mandatory argument

### ISSUE THREAD

**Issue by sportace87** [aws/aws-connected-device-framework#35]
**Aws Connected Device Framework Affected Module(s):**
 

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

The [documentation](https://github.com/aws/aws-connected-device-framework/blob/main/source/docs/deployment.md) does not mention the mandatory -c argument. The [deployment script ](https://github.com/aws/aws-connected-device-framework/blob/main/source/infrastructure/deploy-core.bash) mentions it.

**Current behavior:**

Following the documentation the user is not able to execute the deployment.

**Expected behavior:**

Document the mandatory -c flag and show an example of how to use it.

**Steps to reproduce:**

Navigate to the [documentation](https://github.com/aws/aws-connected-device-framework/blob/main/source/docs/deployment.md) and follow all steps for deploying in [multiple stack mode](https://github.com/aws/aws-connected-device-framework/blob/main/source/docs/deployment.md#deploying-cdf-core-in-multiple-stack-mode).

**Additional Information:**

**Comment by boardthatpowder** [comment]
Fixed as part of https://github.com/aws/aws-connected-device-framework/pull/37.
