### ISSUE TITLE
Search traverser not constructed properly

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-connected-device-framework#41]
**Aws Connected Device Framework Affected Module(s):**
 
assetlibrary

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

A change in version 1.0.1 caused searches having multiple clauses, including a traversal to sometimes not find results, depending if the traversal comes first or second.

**Current behavior:**

Search for a group with the following conditions (note traversal first):
```ts
"type": ["firmware"]
"eq":[
  {
  "traversals":
    [
    {"relation":"installable_on","direction":"out"}
    ],
  "field":"name","value":"my_sku_name"
  },
  {"field":"name","value":"my_firmware_name"}
]
```

This will yield 0 results even if that firmware exists. But if you swap the order in the `eq` array, the search will find a result:

```ts
"type": ["firmware"]
"eq":[
  {"field":"name","value":"my_firmware_name"},
  {
  "traversals":
    [
    {"relation":"installable_on","direction":"out"}
    ],
  "field":"name","value":"my_sku_name"
  }
]
```

**Expected behavior:**

No matter the order in the `eq` array - the same search result should show.

**Steps to reproduce:**

See above

**Additional Information:**

I believe this is because of how the gremlin queries are generated. Looking at the assetlibrary logs, having the traversal first (generating no search results) generates a Search Traverser that looks like this:

> search.full.dao search: traverser:
"[[\"V\"],[\"as\",\"a\"],
[\"select\",\"a\"],
  [\"hasLabel\",\"firmware\"],
[\"select\",\"a\"],
  [\"out\",\"installable_on\"],[\"has\",\"name\",\"my_sku_name\"],
[\"has\",\"name\",\"my_firmware_name\"],
[\"select\",\"a\"],[\"dedup\"],[\"fold\"],[\"unfold\"],[\"as\",\"matched\"],
[\"select\",\"matched\"],[\"dedup\"],[\"range\",0,200],[\"valueMap\"],[\"with\",\"~tinkerpop.valueMap.tokens\"]]"

Having the traversal last yields a Search Traverser that looks like this:

> search.full.dao search: traverser:
"[[\"V\"],[\"as\",\"a\"],
[\"select\",\"a\"],[\"hasLabel\",\"firmware\"],[\"has\",\"name\",\"my_firmware_name\"],
[\"select\",\"a\"],[\"out\",\"installable_on\"],[\"has\",\"name\",\"my_sku_name\"],
[\"select\",\"a\"],[\"dedup\"],[\"fold\"],[\"unfold\"],[\"as\",\"matched\"],[\"select\",\"matched\"],[\"dedup\"],[\"range\",0,200],[\"valueMap\"],[\"with\",\"~tinkerpop.valueMap.tokens\"]]"

I think this is due to the addition of the "select" when the a traversal is present.

https://github.com/aws/aws-connected-device-framework/blob/1bd30255402e8dc00267d6c398da272f6191029e/source/packages/services/assetlibrary/src/search/search.full.dao.ts#L161

If you let me know the general idea you'd like to see for a fix, I'm happy to implement it.

**Comment by boardthatpowder** [comment]
Updated integration tests to test for this scenario. Confirmed happening on 1.0.3.

**Comment by boardthatpowder** [comment]
Fixed in https://github.com/aws/aws-connected-device-framework/releases/tag/1.0.4.
