### ISSUE TITLE
Neptune: Ability to create a replica instance with deploy command

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-connected-device-framework#44]
**Aws Connected Device Framework Affected Module(s):**
 
assetlibrary

**I'm submitting a ...**

- [ ] bug report
- [x] feature request

**Description:**

cfn-neptune.yaml appears to have the ability to specify a replica instance, but there's no way, from the deployment script, to specify to turn that functionality on.

**Current behavior:**

No way, from the deployment script, to specify a Neptune replica instance

**Expected behavior:**

A flag in the deployment script that sets the replica instance flag to true

**Steps to reproduce:**

**Additional Information:**
I'm not sure if this is intended behavior. I'm happy to write the fix if this is something the team wants to have. Just wanted to start the conversation.

**Comment by boardthatpowder** [comment]
Hi Aaron. We have a new cli wizard based installer which we will be releasing soon once we have wrapped up reviews and testing. We implemented this to overcome limitations of the existing script based deployments such as being able to provide values for more Cloudformation templates such as Neptune replicas. This new cli wizard installer will replace the script method.

**Comment by aaronatbissell** [comment]
Saw this was implemented in the new `cdf-cli`. Looks good to me!
