### ISSUE TITLE
cdf installer returns exit code 0 on failures

### ISSUE THREAD

**Issue by TonySherman** [aws/aws-connected-device-framework#72]
**Aws Connected Device Framework Affected Module(s):**
 
installer

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

When the installer fails, an exit code of 0 is still returned. This is problematic for CICD since pipelines appear to pass when they don't.

**Current behavior:**

A failed install returns an exit code of 0

**Expected behavior:**

A failed install returns a non zero exit code

**Steps to reproduce:**

Run the cdf-cli deploy command with incorrect arguments. Check exit code.

**Additional Information:**

`AWS_PROFILE=<profile> cdf-cli deploy <env> <region> -c <bad-config-path>`

```
(node:54210) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/config.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:54210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`echo $?` shows `0`

**Comment by TonySherman** [comment]
This looks like it might be related to Listr2. Even if all tasks fail, Listr2 returns a 0 exit code. Not sure if there's a way to change that with Listr2.

**Comment by TonySherman** [comment]
This specific case can be handled in answerStorage.ts if we exit with an error code in the `loadFromFile` function. I can write a PR for that but I don't know if that's a good pattern to call `process.exit(1)` from there.

```
  public async loadFromFile(configLocation: string): Promise<Answers> {
    try {
      const configOnDisk = await fs.readFile(configLocation, "utf8");
      const answers: Answers = Object.assign({}, JSON.parse(configOnDisk), {
        accountId: this.accountId,
        region: this.region,
        environment: this.environment,
      });
      return answers;
    } catch (e) {
      console.log(e);
      process.exit(1);
    }
  }
```

**Comment by TonySherman** [comment]
Submitted PR that will handle cdf-cli deploy failures a bit more inclusively. Not just on invalid file paths.

**Comment by williamsia** [comment]
Hi @TonySherman , thanks for raising this issue and raising the PR. 

Why don't we put the blanket check on `index.ts` to check for all unhandled rejection.

```
process.on('unhandledRejection', function(err) {
	console.log(err)
    process.exit(1)
});
```

We'll put this fix on our next release. In the meantime if this is blocking you on your CICD, you can temporarily run the deployment by running this command on your CICD script

```
node --unhandled-rejections=warn-with-error-code dist/index.js deploy $ENVIRONMENT $AWS_REGION -c $CONFIG_FILE
```

This will ensure that node will treat all unhandled rejection and return 1 in the exit code.

**Comment by williamsia** [comment]
FYI @TonySherman  , release [1.0.11](https://github.com/aws/aws-connected-device-framework/releases/tag/1.0.11) should addressed this issue, so I will close this issue, thanks for raising this.

**Comment by TonySherman** [comment]
Thanks @williamsia !
